CREATE SCHEMA public;

CREATE TABLE NewTBL (
    id SERIAL PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    password VARCHAR(120) NOT NULL
);

GRANT SELECT, INSERT, UPDATE ON TABLE NewTBL TO public;